export const ACTIONTYPES = {
    'PROFILE': {
        SET_CURRENT_PROFILE : 'auth/SET_CURRENT_PROFILE'
    },
    'USER':{
        LOGIN:'USER_LOGIN'
    },
    'LESSIONS':{
        GET_LESSIONS_BY_CLASSNO_SUBJECT:'GET_LESSIONS_BY_CLASSNO_SUBJECT',
        RESET_LESSIONS_BY_CLASSNO_SUBJECT:'RESET_LESSIONS_BY_CLASSNO_SUBJECT',
        UPDATE_LESSIONS_BY_CLASSNO_SUBJECT:'UPDATE_LESSIONS_BY_CLASSNO_SUBJECT',
        GET_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID:'GET_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID',
        RESET_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID:'RESET_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID',
        UPDATE_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID:'UPDATE_LESSIONS_BY_CLASSNO_SUBJECT_LESSIONID',
    },
    'LEXICON':{
        GET_LEXICON_BY_LEXICON_ID:'GET_LEXICON_BY_LEXICON_ID',
        RESET_LEXICON_BY_LEXICON_ID:'RESET_LEXICON_BY_LEXICON_ID',
        UPDATE_LEXICON_BY_LEXICON_ID:'UPDATE_LEXICON_BY_LEXICON_ID',
    },
    'CRITICAL_THINKING':{
        GET_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID:'GET_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID',
        RESET_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID:'RESET_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID',
        UPDATE_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID:'UPDATE_CRITICAL_THINKING_BY_CRITICAL_THINKING_ID',
    }
}