export const Environment = {
    MW_END_POINT_URL : process.env.REACT_APP_ABCLEARN_API_ENDPOINT,
    FETCH_TIMEOUT: process.env.REACT_APP_FETCH_TIMEOUT,
    ABCLEARN_APP_API_ENDPOINT_URL:process.env.REACT_APP_ABCLEARN_API_ENDPOINT,
    ABCLEARN_APP_GOOGLE_ANALYTICS_ID:process.env.REACT_APP_ABCLEARN_GOOGLE_ANALYTICS_ID,
    S3_URL :process.env.REACT_APP_S3_URL,
    INTRO_URL :process.env.REACT_APP_INTRO_URL,
    LEXICON_IMG_URL:process.env.REACT_APP_LEXICON_IMG_URL,
    VIDEO_URL :process.env.REACT_APP_VIDEO_URL,
    AUDIO_URL:process.env.REACT_APP_AUDIO_URL,
    ACTIVITY_URL:process.env.REACT_APP_ACTIVITY_URL,
    LEXICON_PDF_URL:process.env.REACT_APP_LEXICON_PDF_URL,
    MINDMAP_PDF_URL:process.env.REACT_APP_MINDMAP_PDF_URL
}